[build]
builder = "Nixpacks"
buildCommand = """
cd backend/UrlShortener.Api
dotnet restore
dotnet publish -c Release -o ../../publish
"""

[deploy]
startCommand = "dotnet publish/UrlShortener.Api.dll"
